/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bblioteca;

import DAO.livros_DAO;
import DAO.usuarios_DAO;
import conexao.Livros;
import conexao.Usuarios;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wilker.gandra
 */
public class frm_ver_clientes extends javax.swing.JFrame {

    /**
     * Creates new form frm_ver_clientes
     */
    public frm_ver_clientes() {
        initComponents();
        listar_clientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_clientes = new javax.swing.JTable();
        lbl_sair = new javax.swing.JLabel();
        lbl_titulo_ver_livros = new javax.swing.JLabel();
        lbl_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        tabela_clientes.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        tabela_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Nascimento", "Telefone", "E-mail"
            }
        ));
        jScrollPane1.setViewportView(tabela_clientes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(2, 100, 740, 402);

        lbl_sair.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_sair.setForeground(new java.awt.Color(255, 255, 255));
        lbl_sair.setText("X");
        lbl_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_sairMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_sair);
        lbl_sair.setBounds(710, 0, 40, 60);

        lbl_titulo_ver_livros.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_titulo_ver_livros.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo_ver_livros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo_ver_livros.setText("Lista de Clientes");
        getContentPane().add(lbl_titulo_ver_livros);
        lbl_titulo_ver_livros.setBounds(0, 0, 750, 48);

        lbl_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagem do WhatsApp de 2023-09-11 à(s) 20.19.25.jpg"))); // NOI18N
        getContentPane().add(lbl_fundo);
        lbl_fundo.setBounds(0, 0, 752, 740);

        setSize(new java.awt.Dimension(746, 738));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_sairMouseClicked
       
        frm_menu objfrm_menu = new frm_menu();
                objfrm_menu.setVisible(true);
                
                dispose();
                
    }//GEN-LAST:event_lbl_sairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_ver_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_ver_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_ver_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_ver_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_ver_clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_fundo;
    private javax.swing.JLabel lbl_sair;
    private javax.swing.JLabel lbl_titulo_ver_livros;
    private javax.swing.JTable tabela_clientes;
    // End of variables declaration//GEN-END:variables




private void listar_clientes() {
        try {
            usuarios_DAO objusuariosDAO = new usuarios_DAO();
            DefaultTableModel model = (DefaultTableModel) tabela_clientes.getModel();
            model.setNumRows(0);
            ArrayList<Usuarios> lista = objusuariosDAO.pesquisar_Clientes();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getCpf(),
                    lista.get(num).getNome(),
                    lista.get(num).getNascimento(),
                    lista.get(num).getTelefone(),
                    lista.get(num).getEmail()

                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listar_Clientes" + erro);
        }
    }
    
}
