/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bblioteca;

import DAO.conexao_DAO;
import DAO.funcionarios_DAO;
import DAO.livros_DAO;
import conexao.Funcionarios;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.*;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author will
 */
public class frm_funcionarios extends javax.swing.JFrame {

    /**
     * Creates new form frm_funcionarios
     */
    public frm_funcionarios() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_sair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_cadastrar = new javax.swing.JButton();
        lbl_cpf = new javax.swing.JLabel();
        lbl_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        txt_cpf_funcionarios = new javax.swing.JTextField();
        lbl_nome_funcionarios = new javax.swing.JLabel();
        txt_nome_funcionarios = new javax.swing.JTextField();
        lbl_senha = new javax.swing.JLabel();
        txt_senha_funcionarios = new javax.swing.JTextField();
        lbl_final = new javax.swing.JLabel();
        btn_buscar_funcionarios = new javax.swing.JButton();
        lbl_status = new javax.swing.JLabel();
        lbl_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        btn_sair.setText("Sair");
        btn_sair.setActionCommand("");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sair);
        btn_sair.setBounds(530, 470, 90, 29);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE FUNCIONARIOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 48);

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cadastrar);
        btn_cadastrar.setBounds(110, 470, 101, 29);

        lbl_cpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_cpf.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cpf.setText("CPF: ");
        getContentPane().add(lbl_cpf);
        lbl_cpf.setBounds(90, 200, 60, 25);

        lbl_editar.setText("Editar");
        lbl_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_editarActionPerformed(evt);
            }
        });
        getContentPane().add(lbl_editar);
        lbl_editar.setBounds(310, 470, 90, 29);

        btn_excluir.setText("Excluir");
        getContentPane().add(btn_excluir);
        btn_excluir.setBounds(420, 470, 90, 29);

        txt_cpf_funcionarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txt_cpf_funcionarios);
        txt_cpf_funcionarios.setBounds(180, 200, 310, 33);

        lbl_nome_funcionarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_nome_funcionarios.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nome_funcionarios.setText("Nome:");
        getContentPane().add(lbl_nome_funcionarios);
        lbl_nome_funcionarios.setBounds(90, 250, 70, 25);

        txt_nome_funcionarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txt_nome_funcionarios);
        txt_nome_funcionarios.setBounds(180, 250, 310, 33);

        lbl_senha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_senha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_senha.setText("Senha:");
        getContentPane().add(lbl_senha);
        lbl_senha.setBounds(90, 300, 70, 25);

        txt_senha_funcionarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txt_senha_funcionarios);
        txt_senha_funcionarios.setBounds(180, 300, 310, 33);

        lbl_final.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_final);
        lbl_final.setBounds(551, 208, 0, 17);

        btn_buscar_funcionarios.setText("Buscar");
        btn_buscar_funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_funcionariosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar_funcionarios);
        btn_buscar_funcionarios.setBounds(220, 470, 90, 29);

        lbl_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_status);
        lbl_status.setBounds(0, 225, 545, 0);

        lbl_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagem do WhatsApp de 2023-09-11 à(s) 20.19.25.jpg"))); // NOI18N
        getContentPane().add(lbl_fundo);
        lbl_fundo.setBounds(0, -30, 760, 800);

        setSize(new java.awt.Dimension(754, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        // TODO add your handling code here:
        
        frm_menu objfrm_menu = new frm_menu();
                objfrm_menu.setVisible(true);
                
                dispose();
                
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        // TODO add your handling code here:
        inserir_funcionarios();
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_buscar_funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_funcionariosActionPerformed
        // TODO add your handling code here:
        
        buscar_funcionarios();
    }//GEN-LAST:event_btn_buscar_funcionariosActionPerformed

    private void lbl_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_editarActionPerformed
        // TODO add your handling code here:
        
        Alterar_funcionario();
    }//GEN-LAST:event_lbl_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_funcionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar_funcionarios;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JButton lbl_editar;
    private javax.swing.JLabel lbl_final;
    private javax.swing.JLabel lbl_fundo;
    private javax.swing.JLabel lbl_nome_funcionarios;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JTextField txt_cpf_funcionarios;
    private javax.swing.JTextField txt_nome_funcionarios;
    private javax.swing.JTextField txt_senha_funcionarios;
    // End of variables declaration//GEN-END:variables


   private int inserir_funcionarios(){
       
       try{  
       String cpf, nome, senha;
       
       
       //lbl_status.setText("Funcionario cadastrado com sucesso");
     
       cpf = txt_cpf_funcionarios.getText();
       nome = txt_nome_funcionarios.getText();
       senha = txt_senha_funcionarios.getText();
       
       Funcionarios objfuncionarios = new Funcionarios();
       objfuncionarios.setCpf(cpf);
       objfuncionarios.setNome(nome);
       objfuncionarios.setSenha(senha);
       funcionarios_DAO objfuncionarios_dao = new funcionarios_DAO();
       objfuncionarios_dao.cadastrar_funcionarios(objfuncionarios);
       
        funcionarios_DAO objtfuncionarios_dao = new funcionarios_DAO();
            ResultSet rs_funcionarios_dao = objtfuncionarios_dao.autenticacaoFuncionarios(objfuncionarios);
       
       if(rs_funcionarios_dao.next()){
           lbl_status.setText("Funcionario cadastrado com sucesso :)");
       }else{
            lbl_status.setText("Não foi possivel cadastrar esse funcionario, verifique os dados e tente novamente");
       }
       
       
   }catch (SQLException erro){
       lbl_status.setText("Não foi possivel cadastrar esse funcionario, favor entrar em contato com o administrador do sistema");
   
   }
       
       return 0;
   }
   
   
   private void buscar_funcionarios(){
    
    String sql = " select * from funcionarios where cpf_funcionario = " + txt_cpf_funcionarios.getText();
        try
        {
            livros_DAO objlivros_dao = new livros_DAO();
            ResultSet rs = objlivros_dao.executarconsulta(sql);
            while (rs.next())
            {
                txt_cpf_funcionarios.setText("" + rs.getInt("cpf_funcionario"));
                txt_nome_funcionarios.setText("" + rs.getString("nome_funcionario"));
                txt_senha_funcionarios.setText("" + rs.getString("senha_funcionario"));

            }
        }
        catch (Exception erro)
        {
            System.out.println("Problema na busca");
        }

       

    }
   
   
     private void Alterar_funcionario(){
           
            String cpf, nome,senha;
            
         cpf = txt_cpf_funcionarios.getText();
         nome = txt_nome_funcionarios.getText();
         senha = txt_senha_funcionarios.getText();
         
         
         Funcionarios objfuncionarios = new Funcionarios();
         
         objfuncionarios.setCpf(cpf);
         objfuncionarios.setNome(nome);
         objfuncionarios.setSenha(senha);
         
         funcionarios_DAO objfuncionarios_dao = new funcionarios_DAO();
         objfuncionarios_dao.alterar_funcionarios(objfuncionarios);
         
        }
}
       



