/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bblioteca;

import DAO.funcionarios_DAO;
import conexao.Funcionarios;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.*;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

public class frm_login extends javax.swing.JFrame {

    /**
     * Creates new form frm_login
     */
    public frm_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_login = new javax.swing.JLabel();
        lbl_cpf = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JTextField();
        lbl_senha = new javax.swing.JLabel();
        txt_senha = new javax.swing.JPasswordField();
        btn_entrar = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        lbl_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        lbl_login.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_login.setForeground(new java.awt.Color(255, 255, 255));
        lbl_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_login.setText("Login");
        getContentPane().add(lbl_login);
        lbl_login.setBounds(0, 0, 750, 60);

        lbl_cpf.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_cpf.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cpf.setText("CPF:");
        getContentPane().add(lbl_cpf);
        lbl_cpf.setBounds(40, 210, 51, 21);

        txt_cpf.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(txt_cpf);
        txt_cpf.setBounds(140, 200, 280, 40);

        lbl_senha.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_senha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_senha.setText("Senha:");
        getContentPane().add(lbl_senha);
        lbl_senha.setBounds(40, 280, 80, 21);

        txt_senha.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_senhaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_senha);
        txt_senha.setBounds(140, 270, 280, 40);

        btn_entrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_entrar.setText("Entrar");
        btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_entrar);
        btn_entrar.setBounds(150, 360, 120, 40);

        btn_sair.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sair);
        btn_sair.setBounds(300, 360, 120, 40);

        lbl_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagem do WhatsApp de 2023-09-11 à(s) 20.19.25.jpg"))); // NOI18N
        getContentPane().add(lbl_fundo);
        lbl_fundo.setBounds(0, 0, 760, 740);

        setSize(new java.awt.Dimension(738, 736));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarActionPerformed
       
        Logar();
                
    }//GEN-LAST:event_btn_entrarActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        // TODO add your handling code here:
        
         dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void txt_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_senhaActionPerformed
        // TODO add your handling code here:
         Logar();
    }//GEN-LAST:event_txt_senhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_entrar;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_fundo;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JTextField txt_cpf;
    private javax.swing.JPasswordField txt_senha;
    // End of variables declaration//GEN-END:variables


private void Logar(){
 try {
            String cpf_funcionario, senha_funcionario;

            cpf_funcionario = txt_cpf.getText();
            senha_funcionario = txt_senha.getText();

            Funcionarios objfuncionarios = new Funcionarios();
            objfuncionarios.setCpf(cpf_funcionario);
            objfuncionarios.setSenha(senha_funcionario);
            
            funcionarios_DAO objtfuncionarios_dao = new funcionarios_DAO();
            ResultSet rs_funcionarios_dao = objtfuncionarios_dao.autenticacaoFuncionarios(objfuncionarios);
        
            if(rs_funcionarios_dao.next()){
                //chamar tela
                
                frm_menu objfrm_menu = new frm_menu();
                objfrm_menu.setVisible(true);

                dispose();
            }else{
                //mensagem de erro
                JOptionPane.showMessageDialog(null, "Usuario ou senha invalida");
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null,"frm_login"+ erro);
        }



}
}
