/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bblioteca;

import DAO.funcionarios_DAO;
import DAO.livros_DAO;
import conexao.Funcionarios;
import conexao.Usuarios;
import DAO.usuarios_DAO;
import java.sql.ResultSet;

/**
 *
 * @author will
 */
public class frm_usuarios extends javax.swing.JFrame {

    /**
     * Creates new form frm_usuarios
     */
    public frm_usuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_cpf = new javax.swing.JLabel();
        txt_cpf_usuarios = new javax.swing.JTextField();
        lbl_nome = new javax.swing.JLabel();
        txt_nome_usuarios = new javax.swing.JTextField();
        lbl_nascimento = new javax.swing.JLabel();
        txt_nascimento_usuarios = new javax.swing.JTextField();
        lbl_telefone = new javax.swing.JLabel();
        txt_telefone_usuarios = new javax.swing.JTextField();
        lbl_mail = new javax.swing.JLabel();
        txt_mail_usuarios = new javax.swing.JTextField();
        lbl_senha = new javax.swing.JLabel();
        txt_senha_usuarios = new javax.swing.JPasswordField();
        btn_cad = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        lbl_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Usuarios");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 48);

        lbl_cpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_cpf.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cpf.setText("CPF:");
        getContentPane().add(lbl_cpf);
        lbl_cpf.setBounds(23, 72, 66, 25);
        getContentPane().add(txt_cpf_usuarios);
        txt_cpf_usuarios.setBounds(160, 70, 310, 29);

        lbl_nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_nome.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nome.setText("Nome:");
        getContentPane().add(lbl_nome);
        lbl_nome.setBounds(23, 123, 122, 25);
        getContentPane().add(txt_nome_usuarios);
        txt_nome_usuarios.setBounds(160, 120, 310, 29);

        lbl_nascimento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_nascimento.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nascimento.setText("Nascimento:");
        getContentPane().add(lbl_nascimento);
        lbl_nascimento.setBounds(20, 180, 98, 25);
        getContentPane().add(txt_nascimento_usuarios);
        txt_nascimento_usuarios.setBounds(160, 180, 310, 29);

        lbl_telefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_telefone.setForeground(new java.awt.Color(255, 255, 255));
        lbl_telefone.setText("Telefone:");
        getContentPane().add(lbl_telefone);
        lbl_telefone.setBounds(20, 240, 90, 25);
        getContentPane().add(txt_telefone_usuarios);
        txt_telefone_usuarios.setBounds(160, 240, 310, 29);

        lbl_mail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_mail.setForeground(new java.awt.Color(255, 255, 255));
        lbl_mail.setText("E-Mail:");
        getContentPane().add(lbl_mail);
        lbl_mail.setBounds(20, 310, 70, 25);

        txt_mail_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mail_usuariosActionPerformed(evt);
            }
        });
        getContentPane().add(txt_mail_usuarios);
        txt_mail_usuarios.setBounds(160, 300, 310, 29);

        lbl_senha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_senha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_senha.setText("Senha:");
        getContentPane().add(lbl_senha);
        lbl_senha.setBounds(20, 360, 70, 25);
        getContentPane().add(txt_senha_usuarios);
        txt_senha_usuarios.setBounds(160, 360, 310, 29);

        btn_cad.setText("Cadastar");
        btn_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cad);
        btn_cad.setBounds(80, 490, 96, 29);

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_editar);
        btn_editar.setBounds(330, 490, 90, 29);

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_excluir);
        btn_excluir.setBounds(440, 490, 90, 29);

        btn_sair.setText("Voltar");
        btn_sair.setActionCommand("Voltar");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sair);
        btn_sair.setBounds(570, 490, 90, 29);

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar);
        btn_buscar.setBounds(200, 490, 90, 29);

        lbl_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagem do WhatsApp de 2023-09-11 à(s) 20.19.25.jpg"))); // NOI18N
        getContentPane().add(lbl_fundo);
        lbl_fundo.setBounds(0, -20, 710, 780);

        setSize(new java.awt.Dimension(705, 742));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        // TODO add your handling code here:
        
        frm_menu objfrm_menu = new frm_menu();
                objfrm_menu.setVisible(true);
                
                dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadActionPerformed
        // TODO add your handling code here:
        
        inserir_usuarios();
        
    }//GEN-LAST:event_btn_cadActionPerformed

    private void txt_mail_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mail_usuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mail_usuariosActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        
        buscar_usuarios();
        
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
        
        Alterar_usuario();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_excluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cad;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_fundo;
    private javax.swing.JLabel lbl_mail;
    private javax.swing.JLabel lbl_nascimento;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_telefone;
    private javax.swing.JTextField txt_cpf_usuarios;
    private javax.swing.JTextField txt_mail_usuarios;
    private javax.swing.JTextField txt_nascimento_usuarios;
    private javax.swing.JTextField txt_nome_usuarios;
    private javax.swing.JPasswordField txt_senha_usuarios;
    private javax.swing.JTextField txt_telefone_usuarios;
    // End of variables declaration//GEN-END:variables


    private int inserir_usuarios(){
       
       String cpf, nome, nascimento, telefone, email, senha;
       
      
       cpf = txt_cpf_usuarios.getText();
       nome = txt_nome_usuarios.getText();
       nascimento = txt_nascimento_usuarios.getText();
       telefone = txt_telefone_usuarios.getText();
       email = txt_mail_usuarios.getText();
       senha = txt_senha_usuarios.getText();
      
       
       Usuarios objusuarios = new Usuarios();
       objusuarios.setCpf(cpf);
       objusuarios.setNome(nome);
       objusuarios.setNascimento(nascimento);
       objusuarios.setTelefone(telefone);
       objusuarios.setEmail(email);
       objusuarios.setSenha(senha);
       usuarios_DAO objusuarios_dao = new usuarios_DAO();
       objusuarios_dao.cadastrar_usuarios(objusuarios);
       
       return 0;
   }
    
      private void buscar_usuarios(){
    
    String sql = " select * from usuarios where cpf = " + txt_cpf_usuarios.getText();
        try
        {
            livros_DAO objlivros_dao = new livros_DAO();
            ResultSet rs = objlivros_dao.executarconsulta(sql);
            while (rs.next())
            {
                txt_cpf_usuarios.setText("" + rs.getInt("cpf"));
                txt_nome_usuarios.setText("" + rs.getString("nome"));
                txt_nascimento_usuarios.setText("" + rs.getString("nascimento"));
                txt_telefone_usuarios.setText("" + rs.getString("telefone"));
                txt_mail_usuarios.setText("" + rs.getString("email"));
                txt_senha_usuarios.setText("" + rs.getString("senha"));

            }
        }
        catch (Exception erro)
        {
            System.out.println("Problema na busca");
        }

       

    }
      
      
       private void Alterar_usuario(){
           
            String cpf, nome, nascimento,  telefone, email, senha;
            
         cpf = txt_cpf_usuarios.getText();
         nome = txt_nome_usuarios.getText();
         nascimento = txt_nascimento_usuarios.getText();
         telefone = txt_telefone_usuarios.getText();
         email = txt_mail_usuarios.getText();
         senha = txt_senha_usuarios.getText();
         
         
         Usuarios objusuarios = new Usuarios();
         
         objusuarios.setCpf(cpf);
         objusuarios.setNome(nome);
         objusuarios.setNascimento(nascimento);
         objusuarios.setTelefone(telefone);
         objusuarios.setEmail(email);
         objusuarios.setSenha(senha);
         
         usuarios_DAO objusuarios_dao = new usuarios_DAO();
         objusuarios_dao.alterar_usuarios(objusuarios);
         
        }
}
