/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bblioteca;

import DAO.livros_DAO;
import conexao.Livros;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author will
 */
public class frm_ver_livros extends javax.swing.JFrame {

    /**
     * Creates new form frm_ver_livros
     */
    public frm_ver_livros() {
        initComponents();
        listar_livros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_voltar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_livros = new javax.swing.JTable();
        btn_ver_livros = new javax.swing.JButton();
        txt_qtd = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        txt_id_livro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbl_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        lbl_voltar.setIcon(new javax.swing.ImageIcon("D:\\Users\\wilker.gandra\\Documents\\trabalhos una\\Biblioteca\\imagens\\voltar.png")); // NOI18N
        lbl_voltar.setText("jLabel2");
        lbl_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_voltarMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_voltar);
        lbl_voltar.setBounds(20, 10, 150, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LIVROS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 40);

        tabela_livros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Autor", "Editora", "Publicação", "Genero", "Paginas", "Classificação", "Danificado", "Endereço"
            }
        ));
        jScrollPane1.setViewportView(tabela_livros);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 60, 452, 402);

        btn_ver_livros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_ver_livros.setText("Ver Livros");
        btn_ver_livros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_livrosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ver_livros);
        btn_ver_livros.setBounds(30, 630, 115, 33);

        txt_qtd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_qtd.setText("Sair");
        getContentPane().add(txt_qtd);
        txt_qtd.setBounds(310, 630, 50, 33);

        btn_buscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.setActionCommand("");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar);
        btn_buscar.setBounds(170, 630, 90, 33);
        getContentPane().add(txt_id_livro);
        txt_id_livro.setBounds(150, 530, 190, 29);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID do livro:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 530, 80, 21);

        lbl_fundo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_fundo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagem do WhatsApp de 2023-09-11 à(s) 20.19.25.jpg"))); // NOI18N
        getContentPane().add(lbl_fundo);
        lbl_fundo.setBounds(0, -210, 760, 1150);

        setBounds(0, 0, 752, 732);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ver_livrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_livrosActionPerformed
        // TODO add your handling code here:
        
        listar_livros();
    }//GEN-LAST:event_btn_ver_livrosActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
      
       
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void lbl_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_voltarMouseClicked

      frm_menu objfrm_menu = new frm_menu();
                objfrm_menu.setVisible(true);
                
                dispose();
    }//GEN-LAST:event_lbl_voltarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_ver_livros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_ver_livros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_ver_livros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_ver_livros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_ver_livros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_ver_livros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_fundo;
    private javax.swing.JLabel lbl_voltar;
    private javax.swing.JTable tabela_livros;
    private javax.swing.JTextField txt_id_livro;
    private javax.swing.JTextField txt_qtd;
    // End of variables declaration//GEN-END:variables

    private void listar_livros() {
        try {
            livros_DAO objlivrosDAO = new livros_DAO();
            DefaultTableModel model = (DefaultTableModel) tabela_livros.getModel();
            model.setNumRows(0);
            ArrayList<Livros> lista = objlivrosDAO.pesquisar_livro();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId(),
                    lista.get(num).getNome(),
                    lista.get(num).getAutor(),
                    lista.get(num).getEditora(),
                    lista.get(num).getPublicacao(),
                    lista.get(num).getGereno(),
                    lista.get(num).getPaginas(),
                    lista.get(num).getClassificacao(),
                    lista.get(num).getDanificado(),
                    lista.get(num).getEndereco()

                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listar_livros" + erro);
        }
    }
    
   
}
