/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bblioteca;
import bblioteca.frm_livros;
import bblioteca.frm_usuarios;


/**
 *
 * @author will
 */
public class frm_menu extends javax.swing.JFrame {

    /**
     * Creates new form frm_menu
     */
    public frm_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_x = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_add_livros = new javax.swing.JLabel();
        lbl_funcionarios = new javax.swing.JLabel();
        lbl_cad_usuarios = new javax.swing.JLabel();
        lbl_ver_livros = new javax.swing.JLabel();
        lbl_emprestimos = new javax.swing.JLabel();
        lbl_ver_clientes = new javax.swing.JLabel();
        lbl_ver_funcionarios = new javax.swing.JLabel();
        lbl_mig_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(20, 30));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        lbl_x.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_x.setForeground(new java.awt.Color(255, 255, 255));
        lbl_x.setText("x");
        lbl_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_xMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_x);
        lbl_x.setBounds(700, 0, 40, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LIBRARY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 64);

        lbl_add_livros.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_add_livros.setForeground(new java.awt.Color(255, 255, 255));
        lbl_add_livros.setText("Adicionar livro");
        lbl_add_livros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_add_livrosMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_add_livros);
        lbl_add_livros.setBounds(20, 260, 280, 32);

        lbl_funcionarios.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_funcionarios.setForeground(new java.awt.Color(255, 255, 255));
        lbl_funcionarios.setText("Cadastrar funcionarios");
        lbl_funcionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_funcionariosMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_funcionarios);
        lbl_funcionarios.setBounds(20, 130, 280, 32);

        lbl_cad_usuarios.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_cad_usuarios.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cad_usuarios.setText("Cadastrar usuarios");
        lbl_cad_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cad_usuariosMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_cad_usuarios);
        lbl_cad_usuarios.setBounds(20, 180, 280, 32);

        lbl_ver_livros.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_ver_livros.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ver_livros.setText("Ver livros");
        lbl_ver_livros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ver_livrosMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_ver_livros);
        lbl_ver_livros.setBounds(20, 380, 135, 32);

        lbl_emprestimos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_emprestimos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_emprestimos.setText("Emprestimos");
        lbl_emprestimos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_emprestimosMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_emprestimos);
        lbl_emprestimos.setBounds(20, 300, 170, 32);

        lbl_ver_clientes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_ver_clientes.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ver_clientes.setText("Ver Clientes");
        lbl_ver_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ver_clientesMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_ver_clientes);
        lbl_ver_clientes.setBounds(20, 340, 170, 32);

        lbl_ver_funcionarios.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_ver_funcionarios.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ver_funcionarios.setText("Ver Funcionarios");
        lbl_ver_funcionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ver_funcionariosMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_ver_funcionarios);
        lbl_ver_funcionarios.setBounds(20, 220, 220, 32);

        lbl_mig_fundo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_mig_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagem do WhatsApp de 2023-09-11 à(s) 20.19.25.jpg"))); // NOI18N
        lbl_mig_fundo.setToolTipText("");
        getContentPane().add(lbl_mig_fundo);
        lbl_mig_fundo.setBounds(0, -10, 760, 750);

        setSize(new java.awt.Dimension(751, 737));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_add_livrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_add_livrosMouseClicked
        // TODO add your handling code here:
        
        frm_livros objfrm_livros = new frm_livros();
         objfrm_livros.setVisible(true);
                
                dispose();
                
    }//GEN-LAST:event_lbl_add_livrosMouseClicked

    private void lbl_funcionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_funcionariosMouseClicked
        // TODO add your handling code here:
        
        frm_funcionarios objfrm_funcionarios = new frm_funcionarios();
         objfrm_funcionarios.setVisible(true);
         
         dispose();
         
    }//GEN-LAST:event_lbl_funcionariosMouseClicked

    private void lbl_cad_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cad_usuariosMouseClicked
        // TODO add your handling code here:
        
        frm_usuarios objfrm_usuarios = new frm_usuarios();
         objfrm_usuarios.setVisible(true);
         
         dispose();
         
    }//GEN-LAST:event_lbl_cad_usuariosMouseClicked

    private void lbl_ver_livrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ver_livrosMouseClicked
        // TODO add your handling code here:
        
        frm_ver_livros objfrm_ver_livros = new frm_ver_livros();
         objfrm_ver_livros.setVisible(true);
         
         dispose();
         
    }//GEN-LAST:event_lbl_ver_livrosMouseClicked

    private void lbl_emprestimosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_emprestimosMouseClicked
        // TODO add your handling code here:
        
        frm_emprestimos objfrm_emprestimos  = new frm_emprestimos ();
         objfrm_emprestimos .setVisible(true);
         
         dispose();
         
    }//GEN-LAST:event_lbl_emprestimosMouseClicked

    private void lbl_xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_xMouseClicked
        dispose();
    }//GEN-LAST:event_lbl_xMouseClicked

    private void lbl_ver_funcionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ver_funcionariosMouseClicked
        
        frm_ver_fucionarios objfrm_funcionarios = new frm_ver_fucionarios();
                objfrm_funcionarios.setVisible(true);
                
                dispose();
    }//GEN-LAST:event_lbl_ver_funcionariosMouseClicked

    private void lbl_ver_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ver_clientesMouseClicked
      
        frm_ver_clientes objfrm_clientes = new frm_ver_clientes();
                objfrm_clientes.setVisible(true);
                
                dispose();
        
    }//GEN-LAST:event_lbl_ver_clientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_add_livros;
    private javax.swing.JLabel lbl_cad_usuarios;
    private javax.swing.JLabel lbl_emprestimos;
    private javax.swing.JLabel lbl_funcionarios;
    private javax.swing.JLabel lbl_mig_fundo;
    private javax.swing.JLabel lbl_ver_clientes;
    private javax.swing.JLabel lbl_ver_funcionarios;
    private javax.swing.JLabel lbl_ver_livros;
    private javax.swing.JLabel lbl_x;
    // End of variables declaration//GEN-END:variables
}
